### ISSUE TITLE
Static-like playback when using Snapdroid 0.20.0

### ISSUE THREAD

**Issue by ChrisIossa** [badaix/snapdroid#27]
Hi, I've been experiencing a bug ever since upgrading to version 0.20.0 of Snapdroid. I upgraded Snapserver and Snapdroid to 0.20.0 around the same time. However, when using Snapdroid for playback, all I get is a distorted sound similar to TV static. If I rollback Snapdroid to 0.19.0, everything works fine. 

The Snapserver is running on a Raspberry Pi 4 under Raspbian.
Snapdroid is running on a Moto X4 running Android 9

Here is a client log captured using `adb`.

```07-02 13:15:02.292 26610 26610 D Service : start host: 10.0.0.93, port: 1704
07-02 13:15:02.293 26610 26610 D Service : Running on a non-TV Device
07-02 13:15:02.295 26610 26610 D Service : startProcess
07-02 13:15:02.296 26610 26610 I Service : Configured engine: Auto, active engine: oboe, sampleformat: 48000:16:*
07-02 13:15:02.700 26610 28892 D Main    : onPlayerStart
07-02 13:15:02.701 26610 28892 D Main    : [Info] (Connection) Resolving host IP for: 10.0.0.93
07-02 13:15:02.701 26610 26610 D Main    : updateStartStopMenuItem: ic_media_stop
07-02 13:15:02.701 26610 28892 D Main    : [Info] (Connection) Connecting
07-02 13:15:02.723 26610 28892 D Main    : [Notice] (Connection) Connected to 10.0.0.93
07-02 13:15:02.723 26610 28892 D Main    : [Info] (Connection) My MAC: "00:00:00:00:00:00", socket: 7
07-02 13:15:02.742 26610 27870 D TCP     : Received Message: '{"jsonrpc":"2.0","method":"Client.OnConnect","params":{"client":{"config":{"instance":1,"latency":0,"name":"","volume":{"muted":false,"percent":100}},"connected":true,"host":{"arch":"arm64-v8a","ip":"10.0.0.85","mac":"00:00:00:00:00:00","name":"moto x4","os":"Android 9"},"id":"b6cd8afc-91aa-4839-90f5-261b44352590","lastSeen":{"sec":1593710104,"usec":634210},"snapclient":{"name":"Snapclient","protocolVersion":2,"version":"0.20.0"}},"id":"b6cd8afc-91aa-4839-90f5-261b44352590"}}'
07-02 13:15:02.744 26610 28892 D Main    : [Info] (Controller) ServerSettings - buffer: 1880, latency: 0, volume: 100, muted: 0
07-02 13:15:02.754 26610 28892 D Main    : [Info] (Controller) Codec: flac, sampleformat: 48000:24:2
07-02 13:15:02.754 26610 28892 D Main    : [Info] (Player) Player name: oboe, device: default, description: <none>, idx: -1, sharing mode: shared
07-02 13:15:02.754 26610 28892 D Main    : [Info] (Player) Mixer mode: software, parameters: <none>
07-02 13:15:02.754 26610 28892 D Main    : [Info] (Player) Sampleformat: 48000:24:2, stream: 48000:24:2
07-02 13:15:02.754 26610 28892 D Main    : [Info] (OboePlayer) Init start
07-02 13:15:02.754 26610 28892 D Main    : [Info] (OboePlayer) DefaultStreamValues::SampleRate: 48000, DefaultStreamValues::FramesPerBurst: 240
07-02 13:15:02.778 26610 28892 D Main    : [Info] (OboePlayer) BufferSizeInFrames: 480, FramesPerBurst: 240
07-02 13:15:02.778 26610 28892 D Main    : [Info] (OboePlayer) AudioApi: AAudio
07-02 13:15:02.778 26610 28892 D Main    : [Info] (OboePlayer) Init done
07-02 13:15:02.778 26610 28892 D Main    : [Info] (OboePlayer) Start
07-02 13:15:02.780 26610 28892 D Main    : [Info] (Stream) no chunks available
07-02 13:15:03.162 26610 28892 D Main    : [Info] (Controller) diff to server [ms]: -4.25172e+08
07-02 13:15:04.579 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       1       34      0
07-02 13:15:05.004 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       94      32      0
07-02 13:15:06.004 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       317     32      0
07-02 13:15:07.004 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       500     32      0
07-02 13:15:08.004 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       500     32      0
07-02 13:15:09.000 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       500     31      0
07-02 13:15:10.004 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       500     32      0
07-02 13:15:11.004 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       500     32      0
07-02 13:15:12.004 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       500     32      0
07-02 13:15:13.004 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       500     32      0
07-02 13:15:14.004 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       500     32      0
07-02 13:15:15.004 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       500     32      0
07-02 13:15:16.004 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       500     32      0
07-02 13:15:17.004 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       500     32      0
07-02 13:15:18.004 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       500     32      0
07-02 13:15:19.004 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       500     32      0
07-02 13:15:20.004 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       500     32      0
07-02 13:15:21.004 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       500     32      0
07-02 13:15:22.004 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       500     32      0
07-02 13:15:24.004 26610 28892 I chatty  : uid=10365(de.badaix.snapcast) Thread-28 identical 2 lines
07-02 13:15:25.004 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       500     32      0
07-02 13:15:26.004 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       500     32      0
07-02 13:15:27.004 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       500     32      0
07-02 13:15:28.004 26610 28892 I chatty  : uid=10365(de.badaix.snapcast) Thread-28 identical 1 line
07-02 13:15:29.004 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       500     32      0
07-02 13:15:30.004 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       500     32      0
07-02 13:15:31.002 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       500     29      0
07-02 13:15:32.004 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       500     32      0
07-02 13:15:33.006 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       500     30      0
07-02 13:15:34.004 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       500     32      0
07-02 13:15:35.004 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       500     32      0
07-02 13:15:36.004 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       500     32      0
07-02 13:15:37.004 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       500     32      0
07-02 13:15:38.004 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       500     32      0
07-02 13:15:39.004 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       500     32      0
07-02 13:15:40.004 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       500     32      0
07-02 13:15:41.004 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       500     32      0
07-02 13:15:42.004 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       500     32      0
07-02 13:15:43.004 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       500     32      0
07-02 13:15:44.004 26610 28892 D Main    : [Debug] (Stats) Chunk: 0     0       0       0       500     32      0
07-02 13:15:44.637 26610 26610 D Service : stopPlayer
07-02 13:15:44.637 26610 26610 D Service : stopService
07-02 13:15:44.637 26610 26610 D Service : stop
07-02 13:15:44.637 26610 26610 D Service : stopProcess
07-02 13:15:44.638 26610 28892 D Main    : [Info] (Snapclient) Received signal 15: Terminated
07-02 13:15:44.638 26610 28892 D Main    : [Info] (OboePlayer) Stop
07-02 13:15:44.639 26610 28892 W System.err: java.io.IOException: Stream closed
07-02 13:15:44.639 26610 28892 W System.err:    at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:172)
07-02 13:15:44.639 26610 28892 W System.err:    at java.io.BufferedInputStream.read(BufferedInputStream.java:338)
07-02 13:15:44.639 26610 28892 W System.err:    at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:288)
07-02 13:15:44.639 26610 28892 W System.err:    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:351)
07-02 13:15:44.639 26610 28892 W System.err:    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:180)
07-02 13:15:44.639 26610 28892 W System.err:    at java.io.InputStreamReader.read(InputStreamReader.java:184)
07-02 13:15:44.639 26610 28892 W System.err:    at java.io.BufferedReader.fill(BufferedReader.java:172)
07-02 13:15:44.639 26610 28892 W System.err:    at java.io.BufferedReader.readLine(BufferedReader.java:335)
07-02 13:15:44.639 26610 28892 W System.err:    at java.io.BufferedReader.readLine(BufferedReader.java:400)
07-02 13:15:44.639 26610 28892 W System.err:    at de.badaix.snapcast.SnapclientService$1.run(SnapclientService.java:246)
07-02 13:15:44.639 26610 28892 W System.err:    at java.lang.Thread.run(Thread.java:764)
07-02 13:15:44.646 26610 26610 D Main    : onPlayerStop
07-02 13:15:44.646 26610 26610 D Main    : updateStartStopMenuItem: ic_media_play
07-02 13:15:46.425 26610 27870 D TCP     : Received Message: '{"jsonrpc":"2.0","method":"Client.OnDisconnect","params":{"client":{"config":{"instance":1,"latency":0,"name":"","volume":{"muted":false,"percent":100}},"connected":false,"host":{"arch":"arm64-v8a","ip":"10.0.0.85","mac":"00:00:00:00:00:00","name":"moto x4","os":"Android 9"},"id":"b6cd8afc-91aa-4839-90f5-261b44352590","lastSeen":{"sec":1593710147,"usec":285714},"snapclient":{"name":"Snapclient","protocolVersion":2,"version":"0.20.0"}},"id":"b6cd8afc-91aa-4839-90f5-261b44352590"}}'
```

**Comment by badaix** [comment]
The logs are looking fine. Please try updating to v0.23.0
